--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: flux-finals
  name: flux-deployment
spec: 
  ports: ~
  replicas: 5
  selector: 
    matchLabels: 
      app: flux-finals
  template: 
    metadata: 
      labels: 
        app: flux-finals
    spec: 
      containers: 
        - 
          image: "arunima297/finals:v1"
          name: webpage


